decbot_web/urls.py
from django.views.generic.base import RedirectView
from django.urls import include, path

urlpatterns = [
    path(
        "",
        RedirectView.as_view(pattern_name="scores:score-summary", permanent=True),
        name="index",
    ),
    path("quotes/", include("quotes.urls")),
    path("scores/", include("karma.urls")),
    path("factoids/", include("factoids.urls")),
]

karma/urls.py
from django.urls import path, re_path

from . import views

app_name = "scores"
urlpatterns = [
    path("", views.ScoreSummary.as_view(), name="score-summary"),
    re_path(r"^(?P<pk>.+)$", views.ScoreDetail.as_view(), name="score-detail"),
]

quotes/urls.py
from django.urls import path, re_path

from . import views

app_name = "quotes"
urlpatterns = [
    path("", views.QuoteList.as_view(), name="list"),
    re_path(r"^(?P<pk>\d+)$", views.QuoteView.as_view(), name="quote_view"),
]

quotes/models.py
from django.db import models

from django.urls import reverse
from django.utils.timezone import now


class Quote(models.Model):
    id = models.AutoField(db_column="Id", primary_key=True)
    timestamp = models.DateTimeField(db_column="Timestamp", default=now)
    added_by = models.CharField(db_column="AddedBy", max_length=45)
    deleted_by = models.CharField(db_column="DeletedBy", max_length=45, null=True)
    quote = models.TextField(db_column="Quote")
    active = models.BooleanField(db_column="Active", default=True)
    score_up = models.IntegerField(db_column="ScoreUp", default=0)
    score_down = models.IntegerField(db_column="ScoreDown", default=0)

    class Meta:
        db_table = "quotes"
        ordering = ["-timestamp"]

    def get_absolute_url(self):
        return reverse("quotes:quote_view", kwargs={"pk": self.id})

    @property
    def lines(self):
        start = 0
        i = 0
        q = self.quote
        while i >= 0:
            i = q.find("|", i)
            if i > 0:
                if q[i - 1] != "\\":
                    yield q[start:i].strip().replace("\\|", "|")
                    start = i = i + 1
                else:
                    i += 1
        yield q[start:].strip().replace("\\|", "|")

    @lines.setter
    def lines(self, value):
        self.quote = "|".join(value)

    @classmethod
    def all_active(cls):
        return cls.objects.filter(active=True)


# class Vote(models.Model):
#    id = models.IntegerField(primary_key=True)
#    # TODO prefer composite primary key of quote ID and SID
#    #session =
#    #quote = models.ForeignKeyField(
#
#    class Meta:
#        db_table = 'quotes_votes'
#        unique_together = ('sid', 'quote')

quotes/views.py
from quotes.models import Quote

from decbot_web import DecbotListView
from django.views.generic import DetailView


class QuoteList(DecbotListView):
    context_object_name = "quotes"
    queryset = Quote.all_active()
    paginate_by = 20


class QuoteView(DetailView):
    context_object_name = "quote"
    queryset = Quote.all_active()

quotes/templates/quotes/quote.html
<pre>{{ quote.lines|join:"&#10;" }}</pre>
<a class="qid" href="{{ quote.get_absolute_url }}">#{{ quote.id }}</a>
Added by {{ quote.added_by }}
<time datetime="{{ quote.timestamp|date:"c" }}">
    <abbr title="{{ quote.timestamp|date:"Y-m-d H:i" }}">
        {{ quote.timestamp|timesince }} ago
    </abbr>
</time>

quotes/templates/quotes/quote_detail.html
{% extends "base.html" %}

{% block title %}Quote #{{quote.id}}{% endblock %}

{% block content %}

<h2>Quote #{{quote.id}}</h2>
{% include "quotes/quote.html" %}

<nav>
    <a href="{% url "quotes:list" %}">Return to the quotes list</a>.
</nav>
{% endblock %}

quotes/templates/quotes/quote_list.html
{% extends "base.html" %}

{% block title %}Quotes{% endblock %}

{% block content %}
<h2>Quotes</h2>

<ul class="list-unstyled">{% for quote in quotes %}
    <li class="p-2 my-2 rounded bg-light">
        {% include "quotes/quote.html" %}
    </li>
{% endfor %}</ul>

{% include "pagination.html" with page=page_obj kind="quote" only %}
{% endblock %}